### ISSUE TITLE
Кодстайл проекта

### ISSUE THREAD

**Issue by SerafimArts** [LaravelRUS/laravel.ru#29]
## Текущие правила:

```yml
preset: laravel

enabled:
    - phpdoc_align
    - phpdoc_annotation_without_dot
    - phpdoc_link_to_see
    - phpdoc_no_empty_return
    - phpdoc_separation
    - concat_with_spaces

disabled:
    - phpdoc_to_comment
    - concat_without_spaces
```

Следование PSR, думаю, не обсуждается. Как бы что ни нравилось - это можно считать стандартом. Придётся =)

Ниже предлагаю ставить лайки ("За"/"Оставить как есть") и дизлайки ("Против"/"Вернуть всё взад"). 

**Важно**: Также стоит предлагать свои правила конфигов, которые я не учёл в этом списке исправлений, ломающих кодстайл, принятый в Laravel: https://styleci.readme.io/docs/fixers 
Поправить кодстайл во всём проекте - дело одной кнопки, не парьтесь об этом.
